baseURL: https://noble-varghese.github.io/portfolio
# title: charlola.mode
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: /contact/
          weight: 60
        - name: Articles
          url: /articles/
          weight: 40
        - name: Projects
          url: /projects/
          weight: 50

    #  - name: Categories
    #       url: /categories/
    #       weight: 10
    #     - name: new Tab
    #       url: /newtab/
    #       weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Noble Varghese
        description: |

          Hello, I am Noble.
           I am a software developer. 
        

        imageUrl: "https://noble-varghese.github.io/portfolio/images/profile.jpg"
        imageTitle: my image
        imageWidth: 250
        imageHeight: 250
        # buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articlesmm

    socialIcons:
        - name: github
          url: "https://github.com/noble-varghese"
        - name: linkedin
          url: "https://www.linkedin.com/in/noble-k-varghese/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

